### PR TITLE
Fix OutofMemory of Span.ThrowableTransformer.convert2String

### LINKED ISSUE #219: Fix OutofMemory of Span.ThrowableTransformer.convert2String
Based on the community feedback, `Span.ThrowableTransformer.convert2String` has risk of triggering OOM.

So, I recommend to adjuct this method:
1. Restrict message/stack length should be in the `while` loop, to avoid too long stack, even loop cause.
1. Add `catch` for this method, to avoid exception. In some case, the application framework forbid you to get the stack.

### PR DESCRIPTION
**Pull request by ascrutae**
fix #219

### CODE REVIEW

File: apm-commons/apm-trace/src/main/java/org/skywalking/apm/trace/Span.java [hunk 1]
```diff
@@ -293,18 +293,29 @@ public Span log(Throwable t) {
...
+                    }
+
                     causeException.printStackTrace(new java.io.PrintWriter(buf, true));
                     expMessage.append(buf.toString());
                     causeException = causeException.getCause();
+                    currentAppendStackLength += causeExceptionStackLength;
                 }
 
+            } catch (Throwable ee) {
+                expMessage.append("Failed to execute org.skywalking.apm.trace.ThrowableTransformer#convert2String, Exception message : " + ee.getMessage());
```
Comment (wu-sheng) [inline apm-commons/apm-trace/src/main/java/org/skywalking/apm/trace/Span.java]: This is safe mechanism, and the message will be at user UI. So I don't like `Failed to execute org.skywalking.apm.trace.ThrowableTransformer#convert2String,`, please remove them.

If you want add some comments, you can add these `Stack isn't avaible, message is:`
