### PR TITLE
Fix witness class fail, because of different class loaders.

### LINKED ISSUE #189: Witness class mechanism fails, when its classloader is not the default(BootupClassLoader)
`AbstractClassEnhancePluginDefine.classTypePool` is initialized by `TypePool classTypePool = TypePool.Default.ofClassPath();`.

IMO, this has a potential bug, when the witness class can't be loaded by default ClassLoader, witness class resolution will not be resolved.

cc @sky-walking

### PR DESCRIPTION
**Pull request by wu-sheng**
Fix #189.

### CODE REVIEW

File: apm-sniffer/apm-agent-core/src/main/java/org/skywalking/apm/agent/core/plugin/WitnessClassFinder.java [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+    private Map<ClassLoader, TypePool> poolMap = new ConcurrentHashMap<ClassLoader, TypePool>();
+
+    /**
+     * @param witnessClass
+     * @param classLoader for finding the witnessClass
+     * @return true, if the given witnessClass exists, through the given classLoader.
+     */
+    public boolean exist(String witnessClass, ClassLoader classLoader) {
+        ClassLoader mappingKey = classLoader == null ? NullClassLoader.INSTANCE : classLoader;
+        if (!poolMap.containsKey(witnessClass)) {
```
Comment (ascrutae) [inline apm-sniffer/apm-agent-core/src/main/java/org/skywalking/apm/agent/core/plugin/WitnessClassFinder.java]: The judgment will also return false. because The type of poolMap key is Classloder

Comment (wu-sheng) [inline apm-sniffer/apm-agent-core/src/main/java/org/skywalking/apm/agent/core/plugin/WitnessClassFinder.java]: Yes, the key should be `classLoader`. By using double locks, I think we should change the `ConcurrentHashMap` to `HashMap` too.
